<?php

namespace AppBundle\Repository;

/**
 * orderdetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class orderdetailsRepository extends \Doctrine\ORM\EntityRepository
{
}
