<?php

namespace AppBundle\Repository;

/**
 * ordercontroleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ordercontroleRepository extends \Doctrine\ORM\EntityRepository
{
}
