<?php

namespace AppBundle\Repository;

/**
 * producttypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class producttypeRepository extends \Doctrine\ORM\EntityRepository
{
}
